### ISSUE TITLE
No way to get exist statuses of intermediate commands

### ISSUE THREAD

**Issue by gavinwahl** [acatton/python-spm#5]
The returncode of a pipeline is the return code of the last command. There's no way to find out if a command in the middle failed.

```
>>> proc = run('ls', 'nonexistent').pipe('cat')
>>> proc.wait()
ls: cannot access nonexistent: No such file or directory
('', None)
>>> proc.returncode
0
```

**Comment by acatton** [comment]
The `wait()` programming interface needs to be redesigned. I want it to raise a [`CalledProcessError`](https://docs.python.org/2/library/subprocess.html#subprocess.CalledProcessError) when it fails.
